version: "3.8"

services:
  db:
    image: postgres:14.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.list

  app:
    build: .
    container_name: application_films
    restart: on-failure
    expose:
      - 5000
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:



